# Exploratory Data Analysis(EDA)

In [662]:
import pandas as pd
import numpy as np

In [663]:
df=pd.read_csv('pollution_raw_data.csv', encoding='latin1')

In [664]:
df.head()

,Record_ID,Plant_ID,Stack_ID,Source_Type,TS,PM2_5,SO2,NOx,Unit,LatLon,...,Wind_speed_m_s,Wind_dir_deg,Temp_C,RH_pct,Jurisdiction,Regulation_version,Pollutant_standard_hourly,Pollutant_standard_daily,Raw_note,Inspector_notes
0,E103669,PL-11,ST-035,stack,08-03-2026 19:28,59.101,39.112,89.258,ug/m3,"14.4257, 79.5948",...,13.05,202.7,15.6,31.1,Tamil Nadu,CPCB-2025,116.8,86.2,contains pii: John Doe,no issues observed
1,E114788,PL-05,ST-038,ambient,31-03-2026 14:14,83.134,26.186,27.840,UG/M3,"15.5940 , 79.9476",...,13.18,157.8,17.5,56.8,Tamil Nadu,CPCB-2025,65.0,50.8,manual note,NaN
2,E112496,PL-10,ST-036,lab,26-03-2026 21:23,299.073,59.344,29.127,mg/Nm3,"13.6265, 78.4542",...,2.62,37.3,23.8,70.6,Maharashtra,CPCB-2025,190.6,70.8,contains pii: John Doe,contact Mr. X
3,E103781,PL-04,ST-007,stack,09-03-2026 24:52,39.035,24.661,56.553,Âµg/mÂ³,"13.9342, 76.9687",...,12.85,60.4,29.0,84.1,Maharashtra,CPCB-2023,157.1,98.8,manual note,NaN
4,E100116,PL-06,ST-003,lab,01-03-2026 06:15,146.540,47.534,48.502,mg/nm3,"14.7164, 80.5555",...,12.84,60.3,18.5,54.7,Tamil Nadu,CPCB-2025,156.8,53.2,OK,NaN

In [665]:
df.tail()

,Record_ID,Plant_ID,Stack_ID,Source_Type,TS,PM2_5,SO2,NOx,Unit,LatLon,...,Wind_speed_m_s,Wind_dir_deg,Temp_C,RH_pct,Jurisdiction,Regulation_version,Pollutant_standard_hourly,Pollutant_standard_daily,Raw_note,Inspector_notes
15245,E105191,PL-11,ST-035,ambient,11-03-2026 20:28,158.509,9.663,40.921,ug/m3,"14.4257, 79.5948",...,11.70,220.9,23.6,91.7,Maharashtra,CPCB-2023,130.7,79.3,inspection note,contact Mr. X
15246,E113418,PL-09,ST-039,stack,28-03-2026 17:28,44.551,53.984,28.461,UG/M3,"13.3116 , 81.6812",...,9.97,171.1,18.1,68.8,Karnataka,CPCB-2024,59.7,41.0,contains pii: John Doe,stack access restricted
15247,E105390,PL-17,ST-014,stack,12-03-2026 07:11,355.883,41.063,65.655,UG/M3,"13.4940, 76.0448",...,9.23,195.0,28.5,84.8,Tamil Nadu,CPCB-2024,51.7,89.5,inspection note,NaN
15248,E100860,PL-06,ST-003,stack,02-03-2026 19:14,175.051,62.552,43.249,Âµg/mÂ³,"14.7164, 80.5555",...,8.80,314.6,19.9,74.7,Tamil Nadu,CPCB-2025,179.3,40.2,inspection note,contact Mr. X
15249,E107270,PL-10,ST-036,inspection,16-03-2026 04:39,89.395,160.166,56.575,mg/Nm3,"13.6265, 78.4542",...,12.05,135.8,35.8,60.9,Tamil Nadu,CPCB-2023,101.4,40.3,manual note,no issues observed

In [666]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15250 entries, 0 to 15249
Data columns (total 41 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Record_ID                  15250 non-null  object
 1   Plant_ID                   15250 non-null  object
 2   Stack_ID                   15250 non-null  object
 3   Source_Type                15250 non-null  object
 4   TS                         15250 non-null  object
 5   PM2_5                      14943 non-null  float64
 6   SO2                        14926 non-null  float64
 7   NOx                        14970 non-null  float64
 8   Unit                       15250 non-null  object
 9   LatLon                     15250 non-null  object
 10  Status                     15250 non-null  object
 11  Sensor_serial              15250 non-null  object
 12  Instrument_type            15250 non-null  object
 13  Manufacturer               15250 non-null  object
 14  Calibration_span_factor    15250 non-null  float64
 15  Calibration_zero_offset    15250 non-null  float64
 16  Last_calibration_ts        10706 non-null  object
 17  Next_calibration_due       10681 non-null  object
 18  LOD_PM2_5                  15250 non-null  float64
 19  LOD_SO2                    15250 non-null  float64
 20  LOD_NOx                    15250 non-null  float64
 21  Maintenance_event_ID       1194 non-null   object
 22  Maintenance_start_ts       1194 non-null   object
 23  Maintenance_end_ts         1194 non-null   object
 24  Maintenance_type           1194 non-null   object
 25  Maintenance_notes          896 non-null    object
 26  Lab_sample_ID              2334 non-null   object
 27  Lab_received_ts            2334 non-null   object
 28  Lab_result_entry_ts        2334 non-null   object
 29  Analyst_ID                 2334 non-null   object
 30  Double_entry_check_flag    2334 non-null   float64
 31  Wind_speed_m_s             15250 non-null  float64
 32  Wind_dir_deg               15250 non-null  float64
 33  Temp_C                     15250 non-null  float64
 34  RH_pct                     15250 non-null  float64
 35  Jurisdiction               15250 non-null  object
 36  Regulation_version         15250 non-null  object
 37  Pollutant_standard_hourly  15250 non-null  float64
 38  Pollutant_standard_daily   15250 non-null  float64
 39  Raw_note                   15250 non-null  object
 40  Inspector_notes            11544 non-null  object
dtypes: float64(15), object(26)
memory usage: 4.8+ MB

In [667]:
df.describe()

,PM2_5,SO2,NOx,Calibration_span_factor,Calibration_zero_offset,LOD_PM2_5,LOD_SO2,LOD_NOx,Double_entry_check_flag,Wind_speed_m_s,Wind_dir_deg,Temp_C,RH_pct,Pollutant_standard_hourly,Pollutant_standard_daily
count,14943.000000,14926.000000,14970.000000,15250.000000,15250.000000,15250.000000,15250.000000,15250.000000,2334.000000,15250.000000,15250.000000,15250.000000,15250.000000,15250.000000,15250.000000
mean,138.556204,585.147477,54.623531,1.014270,0.002284,5.509156,2.993194,4.523609,0.502999,7.539279,181.213292,25.965272,59.124485,125.370275,62.300892
std,114.895895,7389.161033,38.777999,0.037453,1.153595,2.598134,1.153691,2.026407,0.500098,4.352090,104.248739,9.203667,22.400592,43.190086,21.679210
min,-862.202000,3.919000,0.000000,0.950000,-1.999900,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,10.000000,20.000000,50.000000,25.000000
25%,67.164500,20.072500,28.592000,0.981800,-1.007500,3.250000,2.000000,2.780000,0.000000,3.700000,91.400000,18.000000,39.600000,88.000000,43.000000
50%,110.312000,29.987000,44.628500,1.014000,0.013700,5.510000,2.990000,4.540000,1.000000,7.580000,181.200000,25.900000,59.200000,125.300000,62.200000
75%,177.364000,45.234750,68.461500,1.046500,0.997200,7.770000,3.990000,6.280000,1.000000,11.327500,273.000000,33.900000,78.300000,162.700000,81.000000
max,1336.658000,99999.000000,436.078000,1.080000,1.999600,10.000000,5.000000,8.000000,1.000000,15.000000,360.000000,42.000000,98.000000,200.000000,100.000000

In [668]:
df.describe(include='object')

,Record_ID,Plant_ID,Stack_ID,Source_Type,TS,Unit,LatLon,Status,Sensor_serial,Instrument_type,...,Maintenance_type,Maintenance_notes,Lab_sample_ID,Lab_received_ts,Lab_result_entry_ts,Analyst_ID,Jurisdiction,Regulation_version,Raw_note,Inspector_notes
count,15250,15250,15250,15250,15250,15250,15250,15250,15250,15250,...,1194,896,2334,2334,2334,2334,15250,15250,15250,11544
unique,15000,20,25,4,12807,5,61,9,13791,3,...,4,3,2290,2294,2291,2000,4,3,4,3
top,E113420,PL-15,ST-007,stack,17-03-2026 08:54,ug/m3,"14.3140, 78.4597",fault,SN69616,AQI,...,corrective,zero drift noted,LS417962,2026-03-24 20:51:05,2026-03-20 15:56:23,AN3568,Tamil Nadu,CPCB-2025,OK,no issues observed
freq,3,806,1184,8430,5,3092,727,2253,5,5099,...,318,320,2,2,3,4,3862,5117,3854,3903

In [669]:
df.shape

(15250, 41)

In [670]:
df.columns

Index(['Record_ID', 'Plant_ID', 'Stack_ID', 'Source_Type', 'TS', 'PM2_5',
       'SO2', 'NOx', 'Unit', 'LatLon', 'Status', 'Sensor_serial',
       'Instrument_type', 'Manufacturer', 'Calibration_span_factor',
       'Calibration_zero_offset', 'Last_calibration_ts',
       'Next_calibration_due', 'LOD_PM2_5', 'LOD_SO2', 'LOD_NOx',
       'Maintenance_event_ID', 'Maintenance_start_ts', 'Maintenance_end_ts',
       'Maintenance_type', 'Maintenance_notes', 'Lab_sample_ID',
       'Lab_received_ts', 'Lab_result_entry_ts', 'Analyst_ID',
       'Double_entry_check_flag', 'Wind_speed_m_s', 'Wind_dir_deg', 'Temp_C',
       'RH_pct', 'Jurisdiction', 'Regulation_version',
       'Pollutant_standard_hourly', 'Pollutant_standard_daily', 'Raw_note',
       'Inspector_notes'],
      dtype='object')

In [671]:
print(df.columns.tolist())

['Record_ID', 'Plant_ID', 'Stack_ID', 'Source_Type', 'TS', 'PM2_5', 'SO2', 'NOx', 'Unit', 'LatLon', 'Status', 'Sensor_serial', 'Instrument_type', 'Manufacturer', 'Calibration_span_factor', 'Calibration_zero_offset', 'Last_calibration_ts', 'Next_calibration_due', 'LOD_PM2_5', 'LOD_SO2', 'LOD_NOx', 'Maintenance_event_ID', 'Maintenance_start_ts', 'Maintenance_end_ts', 'Maintenance_type', 'Maintenance_notes', 'Lab_sample_ID', 'Lab_received_ts', 'Lab_result_entry_ts', 'Analyst_ID', 'Double_entry_check_flag', 'Wind_speed_m_s', 'Wind_dir_deg', 'Temp_C', 'RH_pct', 'Jurisdiction', 'Regulation_version', 'Pollutant_standard_hourly', 'Pollutant_standard_daily', 'Raw_note', 'Inspector_notes']

In [672]:
df.index

RangeIndex(start=0, stop=15250, step=1)

In [673]:
df.dtypes

Record_ID                     object
Plant_ID                      object
Stack_ID                      object
Source_Type                   object
TS                            object
PM2_5                        float64
SO2                          float64
NOx                          float64
Unit                          object
LatLon                        object
Status                        object
Sensor_serial                 object
Instrument_type               object
Manufacturer                  object
Calibration_span_factor      float64
Calibration_zero_offset      float64
Last_calibration_ts           object
Next_calibration_due          object
LOD_PM2_5                    float64
LOD_SO2                      float64
LOD_NOx                      float64
Maintenance_event_ID          object
Maintenance_start_ts          object
Maintenance_end_ts            object
Maintenance_type              object
Maintenance_notes             object
Lab_sample_ID                 object
Lab_received_ts               object
Lab_result_entry_ts           object
Analyst_ID                    object
Double_entry_check_flag      float64
Wind_speed_m_s               float64
Wind_dir_deg                 float64
Temp_C                       float64
RH_pct                       float64
Jurisdiction                  object
Regulation_version            object
Pollutant_standard_hourly    float64
Pollutant_standard_daily     float64
Raw_note                      object
Inspector_notes               object
dtype: object

In [674]:
df.isnull().sum()

Record_ID                        0
Plant_ID                         0
Stack_ID                         0
Source_Type                      0
TS                               0
PM2_5                          307
SO2                            324
NOx                            280
Unit                             0
LatLon                           0
Status                           0
Sensor_serial                    0
Instrument_type                  0
Manufacturer                     0
Calibration_span_factor          0
Calibration_zero_offset          0
Last_calibration_ts           4544
Next_calibration_due          4569
LOD_PM2_5                        0
LOD_SO2                          0
LOD_NOx                          0
Maintenance_event_ID         14056
Maintenance_start_ts         14056
Maintenance_end_ts           14056
Maintenance_type             14056
Maintenance_notes            14354
Lab_sample_ID                12916
Lab_received_ts              12916
Lab_result_entry_ts          12916
Analyst_ID                   12916
Double_entry_check_flag      12916
Wind_speed_m_s                   0
Wind_dir_deg                     0
Temp_C                           0
RH_pct                           0
Jurisdiction                     0
Regulation_version               0
Pollutant_standard_hourly        0
Pollutant_standard_daily         0
Raw_note                         0
Inspector_notes               3706
dtype: int64

In [675]:
df.nunique()

Record_ID                    15000
Plant_ID                        20
Stack_ID                        25
Source_Type                      4
TS                           12807
PM2_5                        14293
SO2                          12879
NOx                          13581
Unit                             5
LatLon                          61
Status                           9
Sensor_serial                13791
Instrument_type                  3
Manufacturer                     4
Calibration_span_factor       1301
Calibration_zero_offset      12504
Last_calibration_ts          10534
Next_calibration_due         10504
LOD_PM2_5                      901
LOD_SO2                        401
LOD_NOx                        701
Maintenance_event_ID          1171
Maintenance_start_ts          1173
Maintenance_end_ts            1173
Maintenance_type                 4
Maintenance_notes                3
Lab_sample_ID                 2290
Lab_received_ts               2294
Lab_result_entry_ts           2291
Analyst_ID                    2000
Double_entry_check_flag          2
Wind_speed_m_s                1500
Wind_dir_deg                  3551
Temp_C                         321
RH_pct                         781
Jurisdiction                     4
Regulation_version               3
Pollutant_standard_hourly     1501
Pollutant_standard_daily       751
Raw_note                         4
Inspector_notes                  3
dtype: int64

# Detailed Data Cleaning Scenarios (15–20)

## 1. Datetime normalization (24:10 → next day 00:10).

In [676]:
df['TS'].head()

0    08-03-2026 19:28
1    31-03-2026 14:14
2    26-03-2026 21:23
3    09-03-2026 24:52
4    01-03-2026 06:15
Name: TS, dtype: object

In [677]:
df['TS'] = df['TS'].astype(str).str.strip()

mask_24 = df['TS'].str.contains(' 24:', na=False)
df.loc[mask_24, 'TS'] = df.loc[mask_24, 'TS'].str.replace(' 24:', ' 00:')

df['TS'] = pd.to_datetime(df['TS'], format='%d-%m-%Y %H:%M', errors='coerce')

df.loc[mask_24, 'TS'] = df.loc[mask_24, 'TS'] + pd.Timedelta(days=1)

In [678]:
df['TS'].head()

0   2026-03-08 19:28:00
1   2026-03-31 14:14:00
2   2026-03-26 21:23:00
3   2026-03-10 00:52:00
4   2026-03-01 06:15:00
Name: TS, dtype: datetime64[ns]

## 2. Unit standardization (ug/m3, µg/m³ → ug/m3).

In [679]:
print(df["Unit"].unique())

['ug/m3' 'UG/M3' 'mg/Nm3' 'Âµg/mÂ³' 'mg/nm3']

In [680]:
df["Unit"] = (df["Unit"].astype(str).str.strip().replace({
        "Âµg/mÂ³": "ug/m3",
        "UG/M3": "ug/m3",
        "mg/nm3": "mg/Nm3"
    })
)

In [681]:
print(df["Unit"].unique())

['ug/m3' 'mg/Nm3']

In [682]:
print(df["Unit"].value_counts())

Unit
ug/m3     9123
mg/Nm3    6127
Name: count, dtype: int64

## 3. Whitespace trimming and casing standardization for status.

In [683]:
print(df["Status"].unique())

['MAINT' 'ok' 'FAULT' ' maint ' 'OK' '   ok  ' 'fault' ' ok ' ' fault ']

In [684]:
df["Status"] = df["Status"].astype(str).str.strip().str.upper()

In [685]:
print(df["Status"].unique())

['MAINT' 'OK' 'FAULT']

In [686]:
df["Status"].value_counts()

Status
OK       6498
FAULT    4509
MAINT    4243
Name: count, dtype: int64

## 4. Coordinate parsing and range validation.

In [687]:
print(df["LatLon"].head())

0       14.4257, 79.5948
1     15.5940 , 79.9476
2       13.6265, 78.4542
3       13.9342, 76.9687
4       14.7164, 80.5555
Name: LatLon, dtype: object

In [688]:
df[["Latitude", "Longitude"]] = df["LatLon"].str.split(",", expand=True)
df["Latitude"] = df["Latitude"].str.strip()
df["Longitude"] = df["Longitude"].str.strip()

df["Latitude"] = pd.to_numeric(df["Latitude"], errors="coerce")
df["Longitude"] = pd.to_numeric(df["Longitude"], errors="coerce")

df.loc[(df["Latitude"] < -90) | (df["Latitude"] > 90), "Latitude"] = pd.NA
df.loc[(df["Longitude"] < -180) | (df["Longitude"] > 180), "Longitude"] = pd.NA

In [689]:
print(df[["Latitude", "Longitude"]].head())

   Latitude  Longitude
0   14.4257    79.5948
1   15.5940    79.9476
2   13.6265    78.4542
3   13.9342    76.9687
4   14.7164    80.5555

In [690]:
df["Latitude"].isnull().sum()

0

In [691]:
df["Longitude"].isnull().sum()

0

In [692]:
df.shape

(15250, 43)

## 5. Negative and impossible concentration checks.

In [693]:
df['PM2_5'].dtype

dtype('float64')

In [694]:
df[(df['PM2_5']<0)]

,Record_ID,Plant_ID,Stack_ID,Source_Type,TS,PM2_5,SO2,NOx,Unit,LatLon,...,Temp_C,RH_pct,Jurisdiction,Regulation_version,Pollutant_standard_hourly,Pollutant_standard_daily,Raw_note,Inspector_notes,Latitude,Longitude
223,E108482,PL-20,ST-023,ambient,2026-03-18 17:03:00,-139.762,32.414,36.626,mg/Nm3,"15.5740, 81.8940",...,36.3,34.2,Karnataka,CPCB-2025,76.5,86.7,manual note,stack access restricted,15.5740,81.8940
262,E102913,PL-15,ST-011,ambient,2026-03-07 05:18:00,-214.446,73.872,23.711,ug/m3,"14.3140, 78.4597",...,13.9,59.2,Karnataka,CPCB-2025,153.1,62.2,manual note,no issues observed,14.3140,78.4597
309,E104043,PL-19,ST-006,ambient,2026-03-09 14:14:00,-147.382,43.076,91.792,mg/Nm3,"13.3429, 80.2667",...,30.6,24.4,Maharashtra,CPCB-2023,163.7,95.5,contains pii: John Doe,stack access restricted,13.3429,80.2667
371,E109249,PL-08,ST-014,ambient,2026-03-20 05:38:00,-399.410,33.326,58.816,mg/Nm3,"15.2354, 77.0165",...,33.0,77.8,Maharashtra,CPCB-2023,111.9,54.4,contains pii: John Doe,no issues observed,15.2354,77.0165
478,E102501,PL-02,ST-016,stack,2026-03-06 09:29:00,-101.015,30.149,7.446,mg/Nm3,"14.2083, 76.6077",...,28.5,37.3,Karnataka,CPCB-2023,81.2,27.8,contains pii: John Doe,NaN,14.2083,76.6077
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14909,E114486,PL-18,ST-007,ambient,2026-03-30 23:13:00,-77.229,NaN,25.597,mg/Nm3,"13.1283, 77.9525",...,20.4,80.0,Karnataka,CPCB-2024,194.8,86.0,OK,contact Mr. X,13.1283,77.9525
14925,E102911,PL-18,ST-007,lab,2026-03-07 05:04:00,-60.431,69.062,49.920,ug/m3,"13.1283, 77.9525",...,15.9,32.3,Tamil Nadu,CPCB-2023,167.4,90.3,contains pii: John Doe,contact Mr. X,13.1283,77.9525
14952,E104389,PL-20,ST-023,stack,2026-03-10 06:41:00,-72.413,44.465,192.454,ug/m3,"15.5740, 81.8940",...,16.6,28.6,Karnataka,CPCB-2025,91.6,37.4,manual note,stack access restricted,15.5740,81.8940
15067,E107721,PL-01,ST-008,stack,2026-03-17 02:18:00,-66.511,48.446,26.510,ug/m3,"14.2265, 77.6492",...,27.4,56.1,Karnataka,CPCB-2025,138.0,38.3,OK,contact Mr. X,14.2265,77.6492
15134,E109268,PL-10,ST-002,ambient,2026-03-20 06:14:00,-56.893,35.148,90.367,ug/m3,"13.6265, 78.4542",...,41.2,59.5,Odisha,CPCB-2024,147.3,93.0,manual note,NaN,13.6265,78.4542

In [695]:
df[df['SO2']<0]

Empty DataFrame
Columns: [Record_ID, Plant_ID, Stack_ID, Source_Type, TS, PM2_5, SO2, NOx, Unit, LatLon, Status, Sensor_serial, Instrument_type, Manufacturer, Calibration_span_factor, Calibration_zero_offset, Last_calibration_ts, Next_calibration_due, LOD_PM2_5, LOD_SO2, LOD_NOx, Maintenance_event_ID, Maintenance_start_ts, Maintenance_end_ts, Maintenance_type, Maintenance_notes, Lab_sample_ID, Lab_received_ts, Lab_result_entry_ts, Analyst_ID, Double_entry_check_flag, Wind_speed_m_s, Wind_dir_deg, Temp_C, RH_pct, Jurisdiction, Regulation_version, Pollutant_standard_hourly, Pollutant_standard_daily, Raw_note, Inspector_notes, Latitude, Longitude]
Index: []

[0 rows x 43 columns]

In [696]:
df[(df['NOx']<0)]

Empty DataFrame
Columns: [Record_ID, Plant_ID, Stack_ID, Source_Type, TS, PM2_5, SO2, NOx, Unit, LatLon, Status, Sensor_serial, Instrument_type, Manufacturer, Calibration_span_factor, Calibration_zero_offset, Last_calibration_ts, Next_calibration_due, LOD_PM2_5, LOD_SO2, LOD_NOx, Maintenance_event_ID, Maintenance_start_ts, Maintenance_end_ts, Maintenance_type, Maintenance_notes, Lab_sample_ID, Lab_received_ts, Lab_result_entry_ts, Analyst_ID, Double_entry_check_flag, Wind_speed_m_s, Wind_dir_deg, Temp_C, RH_pct, Jurisdiction, Regulation_version, Pollutant_standard_hourly, Pollutant_standard_daily, Raw_note, Inspector_notes, Latitude, Longitude]
Index: []

[0 rows x 43 columns]

## 6. Duplicate merge by (Plant_ID, TS).

In [697]:
df['TS'].duplicated().sum()

2752

In [698]:
df['Plant_ID'].duplicated().sum()

15230

In [699]:
df[df.duplicated(subset=['Plant_ID','TS'])]

,Record_ID,Plant_ID,Stack_ID,Source_Type,TS,PM2_5,SO2,NOx,Unit,LatLon,...,Temp_C,RH_pct,Jurisdiction,Regulation_version,Pollutant_standard_hourly,Pollutant_standard_daily,Raw_note,Inspector_notes,Latitude,Longitude
198,E106345,PL-03,ST-015,stack,NaT,25.987,57.568,60.529,mg/Nm3,"15.0862, 78.0219",...,25.7,62.2,Karnataka,CPCB-2023,127.6,65.7,manual note,NaN,15.0862,78.0219
290,E110711,PL-11,ST-013,inspection,NaT,30.626,11.208,44.845,ug/m3,"14.4257, 79.5948",...,36.3,37.5,Tamil Nadu,CPCB-2024,197.1,51.7,contains pii: John Doe,contact Mr. X,14.4257,79.5948
298,E111875,PL-03,ST-015,stack,NaT,63.744,8.408,57.691,ug/m3,"15.0862 , 78.0219",...,26.3,27.0,Maharashtra,CPCB-2024,151.1,50.9,OK,contact Mr. X,15.0862,78.0219
307,E106205,PL-13,ST-038,stack,NaT,47.280,33.017,42.480,mg/Nm3,"14.9332, 81.7124",...,32.5,39.2,Odisha,CPCB-2025,77.1,85.5,OK,no issues observed,14.9332,81.7124
349,E112489,PL-08,ST-014,ambient,NaT,137.141,67.565,117.732,mg/Nm3,"15.2354, 77.0165",...,34.7,57.4,Tamil Nadu,CPCB-2025,53.8,45.3,contains pii: John Doe,contact Mr. X,15.2354,77.0165
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15215,E108666,PL-19,ST-025,lab,2026-03-19 01:25:00,107.726,26.140,105.137,mg/Nm3,"13.3429, 80.2667",...,19.6,67.8,Karnataka,CPCB-2023,195.1,38.7,manual note,contact Mr. X,13.3429,80.2667
15235,E111636,PL-12,ST-027,stack,NaT,54.457,27.098,28.157,ug/m3,"15.1257, 80.9875",...,31.4,33.5,Odisha,CPCB-2023,59.9,82.2,OK,no issues observed,15.1257,80.9875
15241,E106265,PL-14,ST-018,stack,2026-03-14 02:31:00,202.027,7.809,88.906,ug/m3,"13.8778, 78.5787",...,38.1,40.9,Karnataka,CPCB-2023,107.9,32.6,OK,contact Mr. X,13.8778,78.5787
15246,E113418,PL-09,ST-039,stack,2026-03-28 17:28:00,44.551,53.984,28.461,ug/m3,"13.3116 , 81.6812",...,18.1,68.8,Karnataka,CPCB-2024,59.7,41.0,contains pii: John Doe,stack access restricted,13.3116,81.6812
15249,E107270,PL-10,ST-036,inspection,2026-03-16 04:39:00,89.395,160.166,56.575,mg/Nm3,"13.6265, 78.4542",...,35.8,60.9,Tamil Nadu,CPCB-2023,101.4,40.3,manual note,no issues observed,13.6265,78.4542

In [700]:
df.shape

(15250, 43)

In [701]:
df = df.groupby(["Plant_ID", "TS"], as_index=False).first()

In [702]:
df[df.duplicated(subset=['Plant_ID','TS'])]

Empty DataFrame
Columns: [Plant_ID, TS, Record_ID, Stack_ID, Source_Type, PM2_5, SO2, NOx, Unit, LatLon, Status, Sensor_serial, Instrument_type, Manufacturer, Calibration_span_factor, Calibration_zero_offset, Last_calibration_ts, Next_calibration_due, LOD_PM2_5, LOD_SO2, LOD_NOx, Maintenance_event_ID, Maintenance_start_ts, Maintenance_end_ts, Maintenance_type, Maintenance_notes, Lab_sample_ID, Lab_received_ts, Lab_result_entry_ts, Analyst_ID, Double_entry_check_flag, Wind_speed_m_s, Wind_dir_deg, Temp_C, RH_pct, Jurisdiction, Regulation_version, Pollutant_standard_hourly, Pollutant_standard_daily, Raw_note, Inspector_notes, Latitude, Longitude]
Index: []

[0 rows x 43 columns]

In [703]:
df.shape

(14579, 43)

## 7. Sensor span/zero calibration application.

In [704]:
df.loc[1:8,["PM2_5","SO2","NOx","Calibration_span_factor","Calibration_span_factor","Calibration_zero_offset"]]

,PM2_5,SO2,NOx,Calibration_span_factor,Calibration_span_factor,Calibration_zero_offset
1,83.868,29.843,35.493,1.0389,1.0389,-1.0863
2,155.719,18.323,NaN,1.0643,1.0643,1.1168
3,153.279,62.153,28.007,1.0741,1.0741,-0.5143
4,71.153,11.059,122.411,1.0586,1.0586,0.9195
5,279.260,20.385,112.831,1.0500,1.0500,0.6710
6,59.585,30.524,69.094,0.9621,0.9621,-0.9460
7,152.309,15.256,82.440,0.9826,0.9826,-0.5155
8,115.636,13.250,38.925,1.0662,1.0662,1.8583

In [705]:
df[['PM2_5','SO2','NOx']].isnull().sum()

PM2_5    298
SO2      306
NOx      269
dtype: int64

In [706]:
# df[["PM2_5","SO2","NOx"]]=df[["PM2_5","SO2","NOx"]].ffill()

In [707]:
df[['PM2_5','SO2','NOx']].isnull().sum()

PM2_5    298
SO2      306
NOx      269
dtype: int64

In [708]:
df.loc[1:8,["PM2_5","SO2","NOx","Calibration_span_factor","Calibration_span_factor","Calibration_zero_offset"]]

,PM2_5,SO2,NOx,Calibration_span_factor,Calibration_span_factor,Calibration_zero_offset
1,83.868,29.843,35.493,1.0389,1.0389,-1.0863
2,155.719,18.323,NaN,1.0643,1.0643,1.1168
3,153.279,62.153,28.007,1.0741,1.0741,-0.5143
4,71.153,11.059,122.411,1.0586,1.0586,0.9195
5,279.260,20.385,112.831,1.0500,1.0500,0.6710
6,59.585,30.524,69.094,0.9621,0.9621,-0.9460
7,152.309,15.256,82.440,0.9826,0.9826,-0.5155
8,115.636,13.250,38.925,1.0662,1.0662,1.8583

In [709]:
df["Calibrated_PM2_5"] = ((df["PM2_5"] * df["Calibration_span_factor"]) + df["Calibration_zero_offset"]).round(2)

df["Calibrated_SO2"] = ((df["SO2"] * df["Calibration_span_factor"]) + df["Calibration_zero_offset"]).round(2)

df["Calibrated_NOx"] = ((df["NOx"] * df["Calibration_span_factor"]) + df["Calibration_zero_offset"]).round(2)

In [710]:
df.loc[1:8,['PM2_5', 'SO2', 'NOx', 'Calibration_span_factor', 'Calibration_zero_offset', 'Calibrated_PM2_5', 'Calibrated_SO2', 'Calibrated_NOx']]

,PM2_5,SO2,NOx,Calibration_span_factor,Calibration_zero_offset,Calibrated_PM2_5,Calibrated_SO2,Calibrated_NOx
1,83.868,29.843,35.493,1.0389,-1.0863,86.04,29.92,35.79
2,155.719,18.323,NaN,1.0643,1.1168,166.85,20.62,NaN
3,153.279,62.153,28.007,1.0741,-0.5143,164.12,66.24,29.57
4,71.153,11.059,122.411,1.0586,0.9195,76.24,12.63,130.50
5,279.260,20.385,112.831,1.0500,0.6710,293.89,22.08,119.14
6,59.585,30.524,69.094,0.9621,-0.9460,56.38,28.42,65.53
7,152.309,15.256,82.440,0.9826,-0.5155,149.14,14.48,80.49
8,115.636,13.250,38.925,1.0662,1.8583,125.15,15.99,43.36

## 8. Outlier filtering using rolling median and Hampel filters.

In [711]:
df["PM2_5"].head(50)

0     157.841
1      83.868
2     155.719
3     153.279
4      71.153
5     279.260
6      59.585
7     152.309
8     115.636
9     117.073
10        NaN
11     77.162
12     28.502
13     37.906
14    106.327
15    463.138
16     64.009
17    175.676
18     85.460
19     49.303
20     52.789
21    115.683
22     68.451
23    198.628
24    540.499
25    336.394
26     97.529
27    190.446
28    293.643
29    273.433
30    226.608
31     62.956
32    196.822
33     70.939
34    102.528
35     96.964
36    295.353
37    117.087
38    144.998
39    493.849
40     27.306
41     81.188
42     87.635
43    180.599
44     92.008
45     77.381
46    250.514
47    182.231
48     72.037
49    211.903
Name: PM2_5, dtype: float64

In [712]:
rolling_median = df["PM2_5"].rolling(window=5, center=True).median()
mad = (df["PM2_5"] - rolling_median).abs().rolling(window=5, center=True).median()
threshold = 3 * 1.4826 * mad
outliers = (df["PM2_5"] - rolling_median).abs() > threshold
df.loc[outliers, "PM2_5"] = rolling_median[outliers]

In [713]:
df["PM2_5"].head(50)

0     157.841
1      83.868
2     155.719
3     153.279
4      71.153
5     279.260
6      59.585
7     152.309
8     115.636
9     117.073
10        NaN
11     77.162
12     28.502
13     37.906
14    106.327
15    106.327
16     64.009
17    175.676
18     85.460
19     49.303
20     52.789
21    115.683
22     68.451
23    198.628
24    540.499
25    336.394
26     97.529
27    190.446
28    293.643
29    273.433
30    226.608
31     62.956
32    196.822
33     70.939
34    102.528
35     96.964
36    117.087
37    117.087
38    144.998
39    117.087
40     87.635
41     81.188
42     87.635
43     87.635
44     92.008
45     77.381
46    250.514
47    182.231
48     72.037
49    121.902
Name: PM2_5, dtype: float64

In [714]:
print("\nOutliers Corrected:", outliers.sum())

Outliers Corrected: 1366

In [715]:
df["SO2"].head(50)

0        50.282
1        29.843
2        18.323
3        62.153
4        11.059
5        20.385
6        30.524
7        15.256
8        13.250
9        44.245
10       29.542
11       68.037
12       37.313
13       19.239
14       20.450
15       49.970
16      132.740
17       74.619
18       27.863
19       14.222
20       45.584
21       74.562
22       12.647
23       11.833
24       22.507
25       20.111
26       31.655
27       45.409
28       78.148
29       36.302
30       53.387
31       17.221
32       46.204
33    99999.000
34       46.862
35      100.819
36       19.701
37       19.643
38       68.512
39       14.845
40       65.156
41       18.130
42       24.062
43       34.576
44       37.876
45       19.023
46       29.484
47       60.261
48       51.547
49       23.788
Name: SO2, dtype: float64

In [716]:
rolling_median = df["SO2"].rolling(window=5, center=True).median()
mad = (df["SO2"] - rolling_median).abs().rolling(window=5, center=True).median()
threshold = 3 * 1.4826 * mad
outliers = (df["SO2"] - rolling_median).abs() > threshold
df.loc[outliers, "SO2"] = rolling_median[outliers]

In [717]:
df["SO2"].head(50)

0      50.282
1      29.843
2      18.323
3      62.153
4      11.059
5      20.385
6      30.524
7      15.256
8      13.250
9      44.245
10     29.542
11     68.037
12     37.313
13     19.239
14     20.450
15     49.970
16     49.970
17     74.619
18     27.863
19     14.222
20     45.584
21     74.562
22     12.647
23     11.833
24     22.507
25     20.111
26     31.655
27     45.409
28     78.148
29     36.302
30     53.387
31     17.221
32     46.204
33     46.862
34     46.862
35    100.819
36     19.701
37     19.643
38     68.512
39     14.845
40     65.156
41     18.130
42     24.062
43     34.576
44     37.876
45     19.023
46     29.484
47     60.261
48     51.547
49     23.788
Name: SO2, dtype: float64

In [718]:
print("\nOutliers Corrected:", outliers.sum())

Outliers Corrected: 1367

In [719]:
df["NOx"].head(50)

0      26.061
1      35.493
2         NaN
3      28.007
4     122.411
5     112.831
6      69.094
7      82.440
8      38.925
9      35.774
10     98.544
11     54.792
12     45.663
13     69.048
14     50.048
15     56.678
16     32.362
17     37.678
18     34.623
19     59.363
20    119.845
21     38.536
22     33.083
23     74.946
24     69.857
25     64.760
26     63.834
27    123.568
28     78.043
29     41.965
30     45.940
31     42.645
32    105.591
33     47.092
34     48.855
35     62.945
36     24.527
37     79.484
38     35.234
39     87.413
40     39.147
41     35.554
42     27.733
43     88.046
44     22.786
45     14.578
46     49.882
47     40.333
48    124.002
49     60.008
Name: NOx, dtype: float64

In [720]:
rolling_median = df["NOx"].rolling(window=5, center=True).median()
mad = (df["NOx"] - rolling_median).abs().rolling(window=5, center=True).median()
threshold = 3 * 1.4826 * mad
outliers = (df["NOx"] - rolling_median).abs() > threshold
df.loc[outliers, "NOx"] = rolling_median[outliers]

In [721]:
df["NOx"].head(50)

0      26.061
1      35.493
2         NaN
3      28.007
4     122.411
5     112.831
6      69.094
7      82.440
8      38.925
9      35.774
10     98.544
11     54.792
12     45.663
13     69.048
14     50.048
15     56.678
16     32.362
17     37.678
18     34.623
19     59.363
20    119.845
21     38.536
22     33.083
23     74.946
24     69.857
25     64.760
26     63.834
27     64.760
28     78.043
29     41.965
30     45.940
31     42.645
32     47.092
33     47.092
34     48.855
35     62.945
36     24.527
37     79.484
38     35.234
39     39.147
40     39.147
41     35.554
42     27.733
43     27.733
44     22.786
45     14.578
46     49.882
47     40.333
48     60.008
49     60.008
Name: NOx, dtype: float64

In [722]:
print("\nOutliers Corrected:", outliers.sum())

Outliers Corrected: 1318

## 9. Missing gap filling within allowed substitution rules.

In [723]:
df[["PM2_5", "SO2", "NOx"]].head()

     PM2_5     SO2      NOx
0  157.841  50.282   26.061
1   83.868  29.843   35.493
2  155.719  18.323      NaN
3  153.279  62.153   28.007
4   71.153  11.059  122.411

In [724]:
df[["PM2_5", "SO2", "NOx"]].isnull().sum()

PM2_5    298
SO2      306
NOx      269
dtype: int64

In [725]:
df["PM2_5"] = df["PM2_5"].fillna(df["PM2_5"].mean()).round(2)
df["SO2"] = df["SO2"].fillna(df["SO2"].mean()).round(2)
df["NOx"] = df["NOx"].fillna(df["NOx"].mean()).round(2)

In [726]:
df[["PM2_5", "SO2", "NOx"]].isnull().sum()

PM2_5    0
SO2      0
NOx      0
dtype: int64

In [727]:
df[["PM2_5", "SO2", "NOx"]].head()

    PM2_5    SO2     NOx
0  157.84  50.28   26.06
1   83.87  29.84   35.49
2  155.72  18.32   50.14
3  153.28  62.15   28.01
4   71.15  11.06  122.41

## 10. Instrument downtime labeling from maintenance logs.

In [728]:
df['Maintenance_start_ts'].dtype

dtype('O')

In [729]:
df['Maintenance_start_ts'].isnull().sum()

13426

In [730]:
df['Maintenance_start_ts'].head()

0                   None
1                   None
2                   None
3                   None
4    2026-02-27 06:24:53
Name: Maintenance_start_ts, dtype: object

In [731]:
df['Maintenance_start_ts'][0] = pd.Timestamp.today().strftime('%Y-%m-%d %H:%M:%S')

C:\Users\abhil\AppData\Local\Temp\ipykernel_25080\1372393451.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Maintenance_start_ts'][0] = pd.Timestamp.today().strftime('%Y-%m-%d %H:%M:%S')
C:\Users\abhil\AppData\Local\Temp\ipykernel_25080\1372393451.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Maintenance_start_ts'][0] = pd.Timestamp.today().strftime('%Y-%m-%d %H:%M:%S')

In [732]:
df['Maintenance_start_ts'][0]

'2026-07-29 17:11:21'

In [733]:
df['Maintenance_start_ts']=df['Maintenance_start_ts'].ffill()

In [734]:
df['Maintenance_start_ts'].head()

0    2026-07-29 17:11:21
1    2026-07-29 17:11:21
2    2026-07-29 17:11:21
3    2026-07-29 17:11:21
4    2026-02-27 06:24:53
Name: Maintenance_start_ts, dtype: object

In [735]:
df['Maintenance_start_ts'].isnull().sum()

0

In [736]:
df['Maintenance_end_ts'].isnull().sum()

13426

In [737]:
df['Maintenance_end_ts'].head()

0                   None
1                   None
2                   None
3                   None
4    2026-02-27 08:24:53
Name: Maintenance_end_ts, dtype: object

In [738]:
df['Maintenance_end_ts'][0] = pd.Timestamp.today().strftime('%Y-%m-%d %H:%M:%S')

C:\Users\abhil\AppData\Local\Temp\ipykernel_25080\3310717474.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Maintenance_end_ts'][0] = pd.Timestamp.today().strftime('%Y-%m-%d %H:%M:%S')
C:\Users\abhil\AppData\Local\Temp\ipykernel_25080\3310717474.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Maintenance_end_ts'][0] = pd.Timestamp.today().strftime('%Y-%m-%d %H:%M:%S')

In [739]:
df['Maintenance_end_ts'][0]

'2026-07-29 17:11:21'

In [740]:
df['Maintenance_end_ts']=df['Maintenance_end_ts'].ffill()

In [741]:
df['Maintenance_end_ts'].head()

0    2026-07-29 17:11:21
1    2026-07-29 17:11:21
2    2026-07-29 17:11:21
3    2026-07-29 17:11:21
4    2026-02-27 08:24:53
Name: Maintenance_end_ts, dtype: object

In [742]:
df['Maintenance_end_ts'].isnull().sum()

0

In [743]:
df["Downtime_status"] = np.where(
    (df["TS"] >= df["Maintenance_start_ts"]) &
    (df["TS"] <= df["Maintenance_end_ts"]),
    "Yes",
    "No"
)

In [744]:
df['Downtime_status'].unique()

array(['No', 'Yes'], dtype=object)

## 11. Limit of detection (LOD) handling (below LOD → half LOD).

In [745]:
df['LOD_PM2_5'].mean().round(2)

5.51

In [746]:
df['LOD_PM2_5'].head()

0    4.48
1    4.81
2    2.72
3    8.46
4    7.74
Name: LOD_PM2_5, dtype: float64

In [747]:
df['LOD_PM2_5'].tail()

14574    5.91
14575    7.36
14576    4.37
14577    8.48
14578    8.26
Name: LOD_PM2_5, dtype: float64

In [748]:
df['LOD_PM2_5']=np.where(
    df['LOD_PM2_5']<5.51,
    df['LOD_PM2_5']/2,
    df['LOD_PM2_5']
)

In [749]:
df['LOD_PM2_5']

0        2.240
1        2.405
2        1.360
3        8.460
4        7.740
         ...
14574    5.910
14575    7.360
14576    2.185
14577    8.480
14578    8.260
Name: LOD_PM2_5, Length: 14579, dtype: float64

In [750]:
df['LOD_SO2'].mean().round(2)

3.0

In [751]:
df['LOD_SO2'].head()

0    3.49
1    3.23
2    3.78
3    1.76
4    1.78
Name: LOD_SO2, dtype: float64

In [752]:

df['LOD_SO2'].tail()

14574    4.87
14575    4.10
14576    1.95
14577    3.91
14578    3.70
Name: LOD_SO2, dtype: float64

In [753]:
df['LOD_SO2']=np.where(
    df['LOD_SO2']<3.0,
    df['LOD_SO2']/2,
    df['LOD_SO2']
)

In [754]:
df['LOD_SO2']

0        3.490
1        3.230
2        3.780
3        0.880
4        0.890
         ...
14574    4.870
14575    4.100
14576    0.975
14577    3.910
14578    3.700
Name: LOD_SO2, Length: 14579, dtype: float64

In [755]:
df['LOD_NOx'].mean().round(2)

4.53

In [756]:
df['LOD_NOx'].head()

0    2.11
1    7.22
2    5.22
3    6.65
4    4.28
Name: LOD_NOx, dtype: float64

In [757]:
df['LOD_NOx'].tail()

14574    7.12
14575    4.15
14576    7.94
14577    7.50
14578    2.54
Name: LOD_NOx, dtype: float64

In [758]:
df['LOD_NOx']=np.where(
    df['LOD_NOx']<4.53,
    df['LOD_NOx']/2,
    df['LOD_NOx']
)

In [759]:

df['LOD_NOx']

0        1.055
1        7.220
2        5.220
3        6.650
4        2.140
         ...
14574    7.120
14575    2.075
14576    7.940
14577    7.500
14578    1.270
Name: LOD_NOx, Length: 14579, dtype: float64

## 12. Status normalization (OK/FAULT/MAINT).

In [760]:
df["Status"].unique()

array(['MAINT', 'FAULT', 'OK'], dtype=object)

In [761]:
df["Status"] = df["Status"].str.strip().str.upper()

In [762]:
df["Status"].unique()

array(['MAINT', 'FAULT', 'OK'], dtype=object)

In [763]:
df["Status"].value_counts()

Status
OK       6210
FAULT    4317
MAINT    4052
Name: count, dtype: int64

## 13. Stack ID ↔ Plant mapping validation.

In [764]:
df["Plant_Count"] = df.groupby("Stack_ID")["Plant_ID"].transform("nunique")

In [765]:
df["Mapping_Status"] = np.where(
    df["Plant_Count"] > 1,
    "Invalid",
    "Valid")

In [766]:
df.loc[1:10,['Stack_ID','Plant_ID','Mapping_Status']]

   Stack_ID Plant_ID Mapping_Status
1    ST-002    PL-01        Invalid
2    ST-002    PL-01        Invalid
3    ST-002    PL-01        Invalid
4    ST-002    PL-01        Invalid
5    ST-008    PL-01          Valid
6    ST-002    PL-01        Invalid
7    ST-002    PL-01        Invalid
8    ST-008    PL-01          Valid
9    ST-008    PL-01          Valid
10   ST-008    PL-01          Valid

## 14. Unit conversion for mg/Nm3 ↔ ug/m3 when needed.

In [767]:
df["Unit"].value_counts()

Unit
ug/m3     8721
mg/Nm3    5858
Name: count, dtype: int64

In [768]:
x = df["Unit"] == "mg/Nm3"
df.loc[x, "PM2_5"] = df.loc[x, "PM2_5"] * 1000
df.loc[x, "SO2"] = df.loc[x, "SO2"] * 1000
df.loc[x, "NOx"] = df.loc[x, "NOx"] * 1000
df.loc[x, "Unit"] = "ug/m3"

In [769]:
df["Unit"].value_counts()

Unit
ug/m3    14579
Name: count, dtype: int64

In [770]:
df[["PM2_5", "SO2", "NOx", "Unit"]].head()

       PM2_5       SO2        NOx   Unit
0     157.84     50.28      26.06  ug/m3
1   83870.00  29840.00   35490.00  ug/m3
2     155.72     18.32      50.14  ug/m3
3  153280.00  62150.00   28010.00  ug/m3
4   71150.00  11060.00  122410.00  ug/m3

## 15. Ambient vs stack data source tagging.

In [771]:
df["Source_Type"].value_counts()

Source_Type
stack         8055
ambient       3558
lab           2247
inspection     719
Name: count, dtype: int64

In [772]:
dict={
    'stack':'stack',
    'ambient':'ambient',
    'lab':'others',
    'inspection':'others'
}
df['Source_Tagging']=df['Source_Type'].map(dict)

In [773]:
df["Source_Tagging"].value_counts()

Source_Tagging
stack      8055
ambient    3558
others     2966
Name: count, dtype: int64

In [774]:
df.loc[1:10,['Source_Type','Source_Tagging']]

   Source_Type Source_Tagging
1        stack          stack
2      ambient        ambient
3        stack          stack
4   inspection         others
5      ambient        ambient
6      ambient        ambient
7        stack          stack
8        stack          stack
9      ambient        ambient
10       stack          stack

## 16. Lab result digitization QC (double entry checks).

In [775]:
df.columns

Index(['Plant_ID', 'TS', 'Record_ID', 'Stack_ID', 'Source_Type', 'PM2_5',
       'SO2', 'NOx', 'Unit', 'LatLon', 'Status', 'Sensor_serial',
       'Instrument_type', 'Manufacturer', 'Calibration_span_factor',
       'Calibration_zero_offset', 'Last_calibration_ts',
       'Next_calibration_due', 'LOD_PM2_5', 'LOD_SO2', 'LOD_NOx',
       'Maintenance_event_ID', 'Maintenance_start_ts', 'Maintenance_end_ts',
       'Maintenance_type', 'Maintenance_notes', 'Lab_sample_ID',
       'Lab_received_ts', 'Lab_result_entry_ts', 'Analyst_ID',
       'Double_entry_check_flag', 'Wind_speed_m_s', 'Wind_dir_deg', 'Temp_C',
       'RH_pct', 'Jurisdiction', 'Regulation_version',
       'Pollutant_standard_hourly', 'Pollutant_standard_daily', 'Raw_note',
       'Inspector_notes', 'Latitude', 'Longitude', 'Calibrated_PM2_5',
       'Calibrated_SO2', 'Calibrated_NOx', 'Downtime_status', 'Plant_Count',
       'Mapping_Status', 'Source_Tagging'],
      dtype='object')

In [776]:
df['Double_entry_check_flag'].unique()

array([ 1., nan,  0.])

In [777]:
df['Double_entry_check_flag']=df['Double_entry_check_flag'].fillna(0.0)

In [778]:
var={
    0.0:'Failed',
    1.0:'Passed'
}

In [779]:
df['Double_entry_check_flag']=df['Double_entry_check_flag'].map(var)

In [780]:
df['Double_entry_check_flag'].unique()

array(['Passed', 'Failed'], dtype=object)

## 17. Standard time base conversion to IST

In [781]:
df["TS"].head()

0   2026-03-01 00:48:00
1   2026-03-01 06:29:00
2   2026-03-01 10:00:00
3   2026-03-01 10:05:00
4   2026-03-01 10:24:00
Name: TS, dtype: datetime64[ns]

In [782]:
df["TS"] = df["TS"] + pd.Timedelta(hours=5, minutes=30)

In [783]:
df["TS"].head()

0   2026-03-01 06:18:00
1   2026-03-01 11:59:00
2   2026-03-01 15:30:00
3   2026-03-01 15:35:00
4   2026-03-01 15:54:00
Name: TS, dtype: datetime64[ns]

## 18. PII removal in inspection notes

In [784]:
df['Inspector_notes'].unique()

array(['no issues observed', None, 'stack access restricted',
       'contact Mr. X'], dtype=object)

In [785]:
df['Inspector_notes'].head(40)

0          no issues observed
1          no issues observed
2          no issues observed
3                        None
4          no issues observed
5     stack access restricted
6                        None
7     stack access restricted
8                        None
9               contact Mr. X
10                       None
11                       None
12                       None
13                       None
14         no issues observed
15    stack access restricted
16                       None
17                       None
18         no issues observed
19         no issues observed
20              contact Mr. X
21              contact Mr. X
22         no issues observed
23              contact Mr. X
24                       None
25                       None
26         no issues observed
27                       None
28         no issues observed
29              contact Mr. X
30    stack access restricted
31         no issues observed
32         no issues observed
33                       None
34              contact Mr. X
35    stack access restricted
36              contact Mr. X
37         no issues observed
38    stack access restricted
39    stack access restricted
Name: Inspector_notes, dtype: object

In [786]:
pii_names = {"contact Mr. X": '[PERSON]'}
df["Inspector_notes"] = df["Inspector_notes"].replace(pii_names)

In [787]:
df['Inspector_notes']=df['Inspector_notes'].ffill()

In [788]:
df['Inspector_notes'].head(40)

0          no issues observed
1          no issues observed
2          no issues observed
3          no issues observed
4          no issues observed
5     stack access restricted
6     stack access restricted
7     stack access restricted
8     stack access restricted
9                    [PERSON]
10                   [PERSON]
11                   [PERSON]
12                   [PERSON]
13                   [PERSON]
14         no issues observed
15    stack access restricted
16    stack access restricted
17    stack access restricted
18         no issues observed
19         no issues observed
20                   [PERSON]
21                   [PERSON]
22         no issues observed
23                   [PERSON]
24                   [PERSON]
25                   [PERSON]
26         no issues observed
27         no issues observed
28         no issues observed
29                   [PERSON]
30    stack access restricted
31         no issues observed
32         no issues observed
33         no issues observed
34                   [PERSON]
35    stack access restricted
36                   [PERSON]
37         no issues observed
38    stack access restricted
39    stack access restricted
Name: Inspector_notes, dtype: object

## 19. Regulatory threshold joins for each pollutant

In [789]:
df[["PM2_5", "SO2", "NOx", "Pollutant_standard_hourly"]].head()

       PM2_5       SO2        NOx  Pollutant_standard_hourly
0     157.84     50.28      26.06                       91.3
1   83870.00  29840.00   35490.00                       66.5
2     155.72     18.32      50.14                      145.8
3  153280.00  62150.00   28010.00                      107.4
4   71150.00  11060.00  122410.00                      176.4

In [790]:
df["PM2_5_Status"] = np.where(
    df["PM2_5"] > df["Pollutant_standard_hourly"],
    "Exceeded",
    "Within Limit"
)
df["SO2_Status"] = np.where(
    df["SO2"] > df["Pollutant_standard_hourly"],
    "Exceeded",
    "Within Limit"
)
df["NOx_Status"] = np.where(
    df["NOx"] > df["Pollutant_standard_hourly"],
    "Exceeded",
    "Within Limit"
)
df["Compliance_Status"] = np.where(
    (df["PM2_5"] > df["Pollutant_standard_hourly"]) |
    (df["SO2"] > df["Pollutant_standard_hourly"]) |
    (df["NOx"] > df["Pollutant_standard_hourly"]),
    "Exceeded",
    "Within Limit"
)

In [791]:
df[[
    "PM2_5", "PM2_5_Status",
    "SO2", "SO2_Status",
    "NOx", "NOx_Status",
    "Compliance_Status"
]].head()

,PM2_5,PM2_5_Status,SO2,SO2_Status,NOx,NOx_Status,Compliance_Status
0,157.84,Exceeded,50.28,Within Limit,26.06,Within Limit,Exceeded
1,83870.00,Exceeded,29840.00,Exceeded,35490.00,Exceeded,Exceeded
2,155.72,Exceeded,18.32,Within Limit,50.14,Within Limit,Exceeded
3,153280.00,Exceeded,62150.00,Exceeded,28010.00,Exceeded,Exceeded
4,71150.00,Exceeded,11060.00,Exceeded,122410.00,Exceeded,Exceeded

In [792]:
df["PM2_5_Status"].value_counts()

PM2_5_Status
Exceeded        9624
Within Limit    4955
Name: count, dtype: int64

In [793]:
df["SO2_Status"].value_counts()

SO2_Status
Within Limit    8437
Exceeded        6142
Name: count, dtype: int64

In [794]:
df["NOx_Status"].value_counts()

NOx_Status
Within Limit    8084
Exceeded        6495
Name: count, dtype: int64

In [795]:
df["Compliance_Status"].value_counts()

Compliance_Status
Exceeded        9931
Within Limit    4648
Name: count, dtype: int64

## 20. Audit trail creation for corrections

In [796]:
df["Audit_Trail"] = ("Datetime normalized | "
    "Units standardized | "
    "Coordinates validated | "
    "Invalid concentrations cleaned | "
    "Duplicates merged | "
    "Calibration applied | "
    "Outliers filtered | "
    "Missing values filled | "
    "Downtime labeled | "
    "LOD handled | "
    "Status normalized | "
    "Stack-Plant validated | "
    "Unit converted | "
    "Source tagged | "
    "QC checked | "
    "PII removed | "
    "Compliance checked"
)

In [797]:
df[["Audit_Trail"]].head()

                                         Audit_Trail
0  Datetime normalized | Units standardized | Coo...
1  Datetime normalized | Units standardized | Coo...
2  Datetime normalized | Units standardized | Coo...
3  Datetime normalized | Units standardized | Coo...
4  Datetime normalized | Units standardized | Coo...

In [798]:
df.to_csv('cleaned_dataset.csv', index=False)